version: '3.2'
services:

#  frontend:
#    ports:
#      - 4200:4200
#    build: ./Atteste-web
#    depends_on:
#      - core

  core:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:9.5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=atteste
